version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5017;http://+:5016
    ports:
      - "5016"
      - "5017"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ConnectionStrings:DefaultConnection=redisdb:6379
    ports:
      - "5000"
      - "5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5003;http://+:5002
      - ConnectionStrings:DefaultConnection:"Host=localhost;Port=5432;Database=DiscountDb;Username=admin;Password=admin1234"
    ports:
      - "5002"
      - "5003"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5005;http://+:5004
      - "ConnectionString:DefaultConnection=Server=mssqldb;Port=5432;Database=IdentityDb;User Id=sa;Password=Admin123@;"
    ports:
      - "5004"
      - "5005"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  inventory.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5007;http://+:5006
      - ConnectionStrings:DefaultConnection=mongodb://localhost:27017
    ports:
      - "5006"
      - "5007"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5009;http://+:5008
    ports:
      - "5008"
      - "5009"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5011;http://+:5010
      - "ConnectionString:DefaultConnection=Server=mssqldb;Port=5432;Database=PaymentDb;User Id=sa;Password=Admin123@;"
    ports:
      - "5010"
      - "5011"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5013;http://+:5012
    ports:
      - "5012"
      - "5013"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ui.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5015;http://+:5014
      - ConnectionStrings:DefaultConnection=mongodb://localhost:27017
    ports:
      - "5014"
      - "5015"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  service.registry:
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - 8500:8500
  
  redisdb:
    restart: always    
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  postgresdb:
    restart: always    
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  mssqldb:
    restart: always    
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123@
    ports:
      - "1433:1433"

  mysqldb:
    restart: always    
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123@
    ports:
      - "32769:32769"
    volumes:
      -  mysql_data:/var/lib/mysql

  webapp.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
