version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Gateways/APIGateway/Dockerfile
         
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: Services/Inventory/Inventory.API/Dockerfile

  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/Order/Order.API/Dockerfile

  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Services/Product/Product.API/Dockerfile

  ui.api:
    image: ${DOCKER_REGISTRY-}uiapi
    build:
      context: .
      dockerfile: Services/UI/UI.API/Dockerfile

  service.registry:
    image: consul

  redisdb:
    image: redis

  postgresdb:
    image: postgres
  
  mssqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  mysqldb:
    image: mysql

volumes:
  mssql_data:
  mongo_data:
  mysql_data:
  redis_data:
  postgres_data:
